### ISSUE TITLE
TextArea field broken in Contao 3.3

### ISSUE THREAD

**Issue by msfuture** [Craffft/contao-translation-fields#12]
Using the extension in Contao 3.3 everything works fine, except the TextArea input field. 
Looks like Contao places the TinyMCE editor around the outer tag.
![issue_1](https://cloud.githubusercontent.com/assets/6619294/3344091/2bc6fb82-f8a7-11e3-91e8-fd452c921063.JPG)
![issue_2](https://cloud.githubusercontent.com/assets/6619294/3344092/2ed52df8-f8a7-11e3-89a4-7c42702a1a79.JPG)

**Comment by bschi** [comment]
Is this bug been fixed? I have the plugin for a customer in use and desperately need a solution.

**Comment by iCodr8** [comment]
I am working on it. It should be fixed with the current develop branch.
832b5568647017c47bad45b242d5ff5480f50bc2
199faf4b49bbdbab57e909bc7f2c5a7907f9b05c

**Comment by bschi** [comment]
It works. Thank you for the quick turnaround!
