### ISSUE TITLE
Extension is blocking Contao functions 

### ISSUE THREAD

**Issue by pixxelfriend** [Craffft/contao-translation-fields#13]
Hello, 

after installing "translation_fields" with "photoalbums2" i can´t delete any modules, articles or content elements. It seems that something in the extension breaks some Contao functions.

Warning: in_array() expects parameter 2 to be array, null given in system/modules/core/library/Contao/System.php on line 110

#0 [internal function]: __error(2, 'in_array() expe...', '/var/www/xxxxxx...', 110, Array)
#1 system/modules/core/library/Contao/System.php(110): in_array('getInstance', NULL)
#2 system/modules/core/drivers/DC_Table.php(1485): Contao\System->import('\TranslationFie...')
#3 system/modules/translation-fields/driver/DC_Table.php(61): Contao\DC_Table->delete(false)
#4 system/modules/core/classes/Backend.php(430): TranslationFields\DC_Table->delete()
#5 contao/main.php(142): Contao\Backend->getBackendModule('article')
#6 contao/main.php(293): Main->run()
#7 {main}

Fatal error: Class '\TranslationFields\TranslationFieldsBackendHelper' not found in /var/www/xxxxx/html/system/modules/core/library/Contao/System.php on line 110

I have installed 

Contao 3.2.12 
photoalbums2 	1.4.2  Build 6
translation_fields 1.3.3 Build 3

cheers

**Comment by pixxelfriend** [comment]
Hi Again, 

i had a look around the your plugin and i came to the DC_Table.php where you define the oncopy and ondelete callback. It seems that the System.php could not find the class "\TranslationFields\TranslationFieldsBackendHelper" because of the first "\". 

I removed  the \ in both callback definitions and it seems that everything is working correctly now, because the system.php does not thow an error because a missing Class. 
Am i right? ^^

**Comment by iCodr8** [comment]
Sorry, but I can't adjust the error. I am having no problems. But could it be, that you are using an another extension, which injects the DC_Table driver, too?
