### ISSUE TITLE
Contao 3.5 compatibility

### ISSUE THREAD

**Issue by fbender** [Craffft/contao-translation-fields#17]
Will you make this extension compatible with Contao 3.5?

**Comment by iCodr8** [comment]
Yes

**Comment by iCodr8** [comment]
And Contao 4 too, but it will be in a new repository.

**Comment by iCodr8** [comment]
682c368f2213467eb711e2bb2aaa7ddd3272e3c5

**Comment by fbender** [comment]
Cool! Is the C4 version [Craffft/translation-fields-bundle](https://github.com/Craffft/translation-fields-bundle)?

**Comment by iCodr8** [comment]
Yep.

**Comment by iCodr8** [comment]
But, currently it's in beta. I am developing with it.
